(deftheme turboLight "turboLight")

(let ((colors `(
		(fg . "#000000")
		(bg . "#FFFFFF")
		(prompt . "purple")
		(diff-add . "#0000b6b50000")
		(diff-add . "#335533")
		(diff-change . "#ffff50")
		(diff-remove . "#af0000")
		(diff-ancestor . "#5f06b26ccd93")
		(mark . "#00a8af")
		(error . "blue")
		(warning . "LightBlue")
		(info . "CadetBlue")
		(spell-error . "green")
		(spell-warning . "green3")
		(outline-1 . "#4f97d7")
		(outline-1-bg . ,(color-darken-name "#FFFFFF" 10))
		(outline-2 . "#2d9574")
		(outline-2-bg . ,(color-darken-name "#FFFFFF" 15))
		(outline-3 . "#67b11d")
		(outline-3-bg . ,(color-darken-name "#FFFFFF" 20))
		(outline-4 . "#b1951d")
		(outline-4-bg . ,(color-darken-name "#FFFFFF" 25))
		(scrollbar . "light sea green")
		(link . "#67b11d")
		;; Either t or nil. If t then use background color as foreground color
		(hover-overlay-invert-fg . t)
		(hover-overlay-bg . "#7c7c00000000")
		)
	      )
      (theme 'turboLight))
  
  (my/create-theme theme colors nil)
  (provide-theme theme))
